//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFEatTracker
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonActive
    {
        public int id_person_active { get; set; }
        public Nullable<int> id_person { get; set; }
        public Nullable<int> id_activity { get; set; }
        public Nullable<int> id_breakfast { get; set; }
        public Nullable<int> id_lunch { get; set; }
        public Nullable<int> id_dinner { get; set; }
        public Nullable<int> id_othereat { get; set; }
    
        public virtual Activity Activity { get; set; }
        public virtual Breakfast Breakfast { get; set; }
        public virtual Dinner Dinner { get; set; }
        public virtual Lunch Lunch { get; set; }
        public virtual OtherEat OtherEat { get; set; }
        public virtual Person Person { get; set; }
    }
}
